name: Git Hub Action Demo Simple
on: [push]
jobs:
  my-job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am testing simple github action"
      - name: Print Hello
        run: echo "Hello.."
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: List Contents after Checkout 
        run: |
             ls ${{ github.workspace }}
             echo "Finished !!!"
      -name: Print one more to test
       run: echo "Anothen run command used"
