name: Git Hub Action Demo Simple
on:
    push:
        branches:
        - br1
env:
  COMPANY_NAME: Kyndryl        
jobs:
  my-job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am testing simple github action"
      - name: Print Hello
        run: echo "Hello.."

      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: List Contents after Checkout 
        run: |
             BRANCH_NAME=$GITHUB_REF_NAME
             echo "BR NAME:" $BRANCH_NAME
             ls ${{ github.workspace }}
             echo "Finished !!!"
             echo "Compnay Name: " $COMPANY_NAME
             echo "Branch Name :"${{ env.BRANCH_NAME }}
      
