name: Git Hub Action Demo Simple
on: 
  push
   branches:
    - br1
jobs:
  my-job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test simple github action"
      - name: Print Hello
        run: echo "Hello.."
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: List Contents after Checkout 
        run: |
             ls ${{ github.workspace }}
      - run: echo "Finished... !!!"
      
