name: Git Hub Action Demo Simple
on:
    push:
        branches:
        - br1
env:
  COMPANY_NAME: Kyndryl        
jobs:
  my-job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am testing simple github action"
      - name: Print Hello
        run: |
              echo "Hello.."
              BRANCH_NAME=$GITHUB_REF_NAME
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: master
      - name: List Contents after Checkout 
        run: |
             echo "BR NAME:" ${{ env.BRANCH_NAME }}
             ls ${{ github.workspace }}
             cat Text.txt
             echo "Finished !!!"
             echo "Compnay Name: " $COMPANY_NAME
             echo "Branch Name :"$GITHUB_REF_NAME
      
