name: Git Hub Action Demo Simple
on:
    push:
        branches:
        - br1
jobs:
  my-job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "I am testing simple github action"
      - name: Print Hello
        run: |
              echo "Hello.."
              echo "Multiple run example"
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: List Contents after Checkout 
        run: |
             echo "Branch Name:" $GITHUB_REF_NAME
             echo "Workspace dir:" $GITHUB_WORKSPACE
             ls ${{ github.workspace }}
             cat Text.txt
             echo "Finished !!!"