name: Git Hub Action Demo Simple
on:
    push:
        branches:
        - br1
env:
  COMPANY_NAME: Kyndryl        
  BRANCH_NAME: BR-1
jobs:
  my-job1:
    runs-on: ubuntu-latest
    env:
      day: Wednesday
    steps:
      - run: echo "I am testing simple github action"
      - name: Print Hello
        run: |
              echo "Hello..Today is :"
              echo "Today is :$day 
      - name: Checkout Repository
        uses: actions/checkout@v3
#        with:
#          ref: master
      - name: List Contents after Checkout 
        run: |
             echo "BR NAME:" $BRANCH_NAME
             ls ${{ github.workspace }}
             cat Text.txt
             echo "Finished !!!"
             echo "Compnay Name :" $COMPANY_NAME
             echo "Branch Name :" $GITHUB_REF_NAME
             echo "Today :"$day
      
